import { formatDate } from "../utils/dateUtils";

export const RATES_COLUMNS = [
  { key: 'rate_type',      label: 'Rate Type' },
  { key: 'target_type',    label: 'Target Type' },
  { key: 'target_name',    label: 'Target' },
  { key: 'site_name',      label: 'Site' },
  { key: 'unit_price',     label: 'Unit Price' },
  { key: 'effective_from', label: 'Effective From', render: (value) => formatDate(value) },
  { key: 'effective_to',   label: 'Effective To', render: (value) => formatDate(value) },
];

export const RATES_FIELDS = [
  {
    name: 'rate_type',
    label: 'Rate Type',
    type: 'select',
    required: true,
    options: ['EMPLOYEE_COST', 'SUBCONTRACTOR_CONTRACT', 'SUBCONTRACTOR_WORKER_CONTRACT'],
    span: 1,
  },
  {
    name: 'target_type',
    label: 'Target Type',
    type: 'select',
    required: true,
    options: ['EMPLOYEE', 'SUBCONTRACTOR', 'SUBCONTRACTOR_WORKER'],
    span: 1,
  },
  {
    name: 'target_id',
    label: 'Target',
    type: 'autocomplete',
    required: true,
    placeholder: 'Search target...',
    valueKey: 'id',
    labelKey: 'label',
    displayKey: 'target_name',
    options: [],
    span: 1,
  },
  {
    name: 'site_id',
    label: 'Site',
    type: 'autocomplete',
    required: false,
    placeholder: 'Search site...',
    valueKey: 'id',
    labelKey: 'site_name',
    displayKey: 'site_name',
    options: [],
    span: 1,
  },
  {
    name: 'unit_price',
    label: 'Unit Price',
    type: 'number',
    required: true,
    span: 1,
  },
  {
    name: 'effective_from',
    label: 'Effective From',
    type: 'date',
    required: true,
    span: 1,
  },
  {
    name: 'effective_to',
    label: 'Effective To',
    type: 'date',
    required: false,
    span: 1,
  },
];
